[project]
name = "rua-vertex"
version = "0.0.0"
description = "building agentic workflows"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.3",
]

[tool.pytest.ini_options]
pythonpath = "src"